# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
